### ISSUE TITLE
I want to contribute...

### ISSUE THREAD

**Issue by OeildeLynx31** [Magic-Fishes/Ecole-Directe-Plus#1]
Hello ! Votre projet d'école directe plus m'intéresse beaucoup ! Je demande donc si ça serai possible de vous aider ! Je pratique le HTML, CSS et JS, et j'ai déjà de l'expérience avec École Directe [(j'ai fait une extension navigateur avec quelques fonctionnalités utiles...)](https://addons.mozilla.org/fr/firefox/addon/ecole-directe-extra/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)
J'ai plein d'idées, et je pourrais vous aider à construire ce projet !
PS : I spoke in french. If anyone wants me to translate into english, I will do it.

**Comment by Truiteseche** [comment]
Hey merci pour ton message @OeildeLynx31 !
Nous avons jeté oeil à ton extension et c'est franchement réussi, bravo !
Pour ce projet, nous utilisons le framework React, je te conseille de te renseigner sur ce framework si tu ne l'as jamais utilisé,
Si tu as besoin de plus d'information, n'hésite pas à nous contacter nous serions ravis de t'aider (le code peut parfois sembler indigeste parce qu'on sait pas coder mais tkt demande nous),
Sache que ce repository est public et tu devrais normalement pouvoir créer des pull requests comme bon te semble. Ça nous permettra de review ton code et de le push sur la branche principale si il convient (je n'en doute pas)

**Comment by OeildeLynx31** [comment]
Bonjour ! 

> Pour ce projet, nous utilisons le framework React

Pour React, je sais à peu près ce que sait, je l'ai déjà un peu manipulé, mais j'ai jamais programmé vraiment avec à proprement parler.

>  Nous avons jeté oeil à ton extension et c'est franchement réussi, bravo !

Pour mon extension, le meilleur est à venir. 

> Sache que ce repository est public et tu devrais normalement pouvoir créer des pull requests comme bon te semble. 

Sinon, le système, ici, c'est directement pull request? Ou bien vous préférez que je passe d'abord par des issues ? C'est comme vous voulez.

**Comment by OeildeLynx31** [comment]
Au fait, comment on fait le build en local ? J'ai essayé `npm run`, `npm start`, et puis j'ai vu que vous utilisiez `VITE`. J'ai installé, et ça marche toujours pas.

**Comment by Truiteseche** [comment]
> Pour React, je sais à peu près ce que sait, je l'ai déjà un peu manipulé, mais j'ai jamais programmé vraiment avec à proprement parler.

Cool il faut juste que tu maîtrise les bases, on ne fait pas du React OMEGA complexe, je pense qu'il faudrait juste que tu saches :
- Créer un composant fonctionnel, gestion des `props`
- Les hooks de base: `useState`, `useEffect`, `useRef`
- Les injections JSX (ne te fies pas au nom c'est ez) et l'affichage conditionnel

C'est globalement tout.

> Sinon, le système, ici, c'est directement pull request? Ou bien vous préférez que je passe d'abord par des issues ? C'est comme vous voulez.

@saumon-brule et moi-même on se permet de push directement nos commits sur la branche de développement. L'idéal serait que tu ouvres une issue si tu as une idée de feature, pour qu'on puisse en débattre, et si tout le monde est ok tu pourras dev la feature et faire une pull request. Après te gêne pas de faire directement des pull requests si c'est pas une grosse fonctionnalité.

Et voici nos Discord si tu veux communiquer plus facilement :
- saumon_brule
- truite_seche
