### ISSUE TITLE
The selected chart is not saved

### ISSUE THREAD

**Issue by saumon-brule** [Magic-Fishes/Ecole-Directe-Plus#13]
### If you go to see the grades list and come back the the charts, if you selected a different chart than the first one, it is reset to the first one.

- chart :

![image](https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/96207807/ed1bdbc4-fc8c-4bad-a49c-53c3327a3368)

- go to grades :

![image](https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/96207807/46a8af70-f48d-4d62-8535-6784c73e7e5e)

- come back to charts :

![image](https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/96207807/706c664b-a30e-43cb-99f4-7fa7e3204d2b)

**Comment by Ewalwi** [comment]
Is this a real problem ? But I think it can be patched really quickly

**Comment by Ewalwi** [comment]
maybe we should close this issue ?

**Comment by Truiteseche** [comment]
based
