### ISSUE TITLE
[FEATURE REQUEST] Ajouter une sorte de code couleur qui montre l'influence d'une matière sur la moyenne générale

### ISSUE THREAD

**Issue by Fefedu973** [Magic-Fishes/Ecole-Directe-Plus#25]
Ajouter une sorte de code couleur qui montre l'influence d'une matière sur la moyenne générale à la manière de custom directe

**Comment by saumon-brule** [comment]
Pertinent, personne travaille sur les notes actuellement donc ça devrait pas poser de problème si quelqu'un fait une pr pour ça.

**Comment by saumon-brule** [comment]
Sinon je le ferais potentiellement dans un future lointain

**Comment by Fefedu973** [comment]
je le fait
![image](https://github.com/user-attachments/assets/398bde60-fafd-499a-b6f9-ca8aa08183a4)

**Comment by Fefedu973** [comment]
https://github.com/user-attachments/assets/b471f509-a0cc-471f-bca4-2e41d2948bd7
