### ISSUE TITLE
[FEATURE REQUEST] Permetre de lire des anciens devoirs dans le cahier de texte (pas que les futurs) 

### ISSUE THREAD

**Issue by Fefedu973** [Magic-Fishes/Ecole-Directe-Plus#26]
Permetre de lire des anciens devoirs dans le cahier de texte (pas que les futurs) et de voir les contenus de scéances

**Comment by OeildeLynx31** [comment]
> Permetre de lire des anciens devoirs dans le cahier de texte (pas que les futurs) et de voir les contenus de scéances

Je ne sais pas si on te l'a dit depuis, mais c'est prévu, et déjà en partie codé et fonctionnel il me semble.

**Comment by OeildeLynx31** [comment]
On fermera avec la validation de @saumon-brule que c'est bien fait.

**Comment by Fefedu973** [comment]
Oui je sais c'est Moi qui ai dev la feature 😂

**Comment by OeildeLynx31** [comment]
> Oui je sais c'est Moi qui ai dev la feature 😂

ah 😂 ! Est-ce que tu as merge ou pas encore ?

**Comment by OeildeLynx31** [comment]
done in #30
