### ISSUE TITLE
[BUG] La messagerie crash avec le mode streamer:

### ISSUE THREAD

**Issue by M6a5x98** [Magic-Fishes/Ecole-Directe-Plus#53]
**Description du bug**
Si on active le mode streamer et qu'on clique sur l'onglet **_Messagerie_** Ecole Directe Plus crash avec cette erreur `TypeError: undefined is not an object (evaluating 'c.from.name.split') `

**Étapes pour reproduire**
1. Activer le Mode Streamer
2. Aller dans la _**Messagerie**_
4. Voir le bug apparaître ✨

**Comportement attendu**
Que la _**Messagerie**_ s'ouvre sans crasher

**Plateforme:**
 - Appareil: iPad 9
 - OS: iOS 18.1
 - Browser : DuckDuckGo
 - Version : 7.144.0.1

**Précisions:**
La messagerie ne crashe que sur le canal stable

**Comment by Truiteseche** [comment]
Yo
ED a mis à jour son API ce qui fait que les clés dans le JSON de réponse qui concernent le nom des expéditeurs ont changé. Ça a été corrigé ici https://github.com/Magic-Fishes/Ecole-Directe-Plus/commit/43c8c99b26f5ce59e08c9a46418f5c6ee7f68aa1 et ici https://github.com/Magic-Fishes/Ecole-Directe-Plus/commit/53d1a0fe75513bae899ff975a0d2998e0ba2719. Donc normalement le bug a disparu sur la branche de développement.

Les correctifs ont été push sur le canal dev donc si tu peux tester pour confirmer avant de fermer l'issue ça serait cool @M6a5x98

**Comment by M6a5x98** [comment]
C'est bon ça crashe pas sur le canal stable. 
**PS** Quand est-ce que la prochaine version arrive ?

**Comment by Truiteseche** [comment]
> Quand est-ce que la prochaine version arrive ?

Ce soir ou demain 👀 (la plus grosse tâche c'est finir d'écrire le patch notes)
