### ISSUE TITLE
Add option to blur account photo

### ISSUE THREAD

**Issue by OeildeLynx31** [Magic-Fishes/Ecole-Directe-Plus#7]
![image](https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/104771596/28adbf46-cb3e-4fbb-85be-5f6423b2eafd)
It could be with the future photo change parameters.

**Comment by saumon-brule** [comment]
This is actually two really different things, even if it's linked to the profile picture, changing the profile picture and add a blur on it are very different

**Comment by OeildeLynx31** [comment]
Something like this:
![image](https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/104771596/d090249c-ab5e-4c2a-973e-bbea66af8c72)
![image](https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/104771596/f07889d4-7559-4795-9394-852491f0a6cc)

**Comment by Truiteseche** [comment]
Closed by #10
